#!/system/bin/sh

grep -oE 'init_[0-9_]+' /vendor/etc/selinux/nonplat_sepolicy.cil | \
	uniq | \
	sort -n | \
	head -n 1 | \
	sed -E 's/.*init_([0-9]+).*/\1/g' | \
while read version;do
	setprop persist.sys.vndk $version
done

mount -o bind /system/bin/adbd /sbin/adbd
if ( getprop ro.hardware | grep -q kirin970 ) || ( getprop ro.hardware | grep -q hi6250 );then
	FOUND_HUAWEI=1
	setprop persist.sys.bt_acl_bypass true
fi

if getprop ro.vendor.build.fingerprint |grep -qiE '(huawei|honor|hi3660)' || [ -n "$FOUND_HUAWEI" ];then
	FOUND_HUAWEI=1
	setprop persist.sys.overlay.huawei.backlight true
fi
